site_name: Documentation
site_url: https://ms.prizm-energy.com/userguide/

theme:
  name: material
  direction: ltr
  features:
    - navigation.sections
    - content.code.copy

plugins:
  - search
  - i18n:
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          name: English
          build: true
          default: true
        - locale: ar
          name: العربية
          build: true
          site_name: وثائق
          theme:
            direction: rtl
          nav_translations:
            Home: الرئيسية
            RFQ Guide: دليل طلب عروض الأسعار
            Purchases: المشتريات
            Tenders: المناقصات
            Budget: الميزانية
            Resource Manager: مدير الموارد
            Opportunities: الفرص
            RFQ: طلب عروض الأسعار
            Gatepass: تصريح المرور
            Technical Analysis: التحليل الفني
            About: حول

nav:
  - Home: index.md
  - RFQ Guide: guide.md
  - Purchases: purchases.md
  - Tenders: tenders.md
  - Budget: budget.md
  - Resource Manager: resource-manager.md
  - Opportunities: opportunities.md
  - RFQ: rfq.md
  - Gatepass: gatepass.md
  - Technical Analysis: technical-analysis.md
  - About: about.md
