site_name: Documentation

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy

plugins:
  - search
  - i18n:
      languages:
        - locale: en
          name: English
          build: true
          default: true
        - locale: ar
          name: العربية
          build: true

nav:
  - Home: index.en.md
  - RFQ Guide: guide.en.md
  - Purchases: purchases.md
  - Tenders: tenders.md
  - Budget: budget.md
  - Resource Manager: resource-manager.md
  - Opportunities: opportunities.md
  - RFQ: rfq.md
  - Gatepass: gatepass.md
  - Technical Analysis: technical-analysis.md
  - About: about.md