site_name: Prizm Management System Documentation
site_url: https://docs.prizm-energy.com
theme:
  name: readthedocs
nav:
  - Home: index.md
  - Purchases: purchases.md
  - Tenders: tenders.md
  - Budget: budget.md
  - Resource Manager: resource-manager.md
  - Opportunities: opportunities.md
  - RFQ: rfq.md
  - Gatepass: gatepass.md
  - Technical Analysis: technical-analysis.md
  - About: about.md