site_name: Documentation

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy

plugins:
  - i18n:
      default_language: en
      languages:
        en:
          name: English
          direction: ltr
        ar:
          name: العربية
          direction: rtl

nav:
  - Home: index.md
  - Purchases: purchases.md
  - Tenders: tenders.md
  - Budget: budget.md
  - Resource Manager: resource-manager.md
  - Opportunities: opportunities.md
  - RFQ: rfq.md
  - Gatepass: gatepass.md
  - Technical Analysis: technical-analysis.md
  - About: about.md